version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./db:/app/db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
